#!/bin/bash

LOCALDIR=`cd "$( dirname $0 )" && pwd`
cd $LOCALDIR

rm -rf $1/data-app/*

rm -rf $1/app/Cit
rm -rf $1/app/HybridPlatform
rm -rf $1/app/GFTest
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/VoiceAssist
rm -rf $1/priv-app/MiuiVideo
rm -rf $1/priv-app/Music
rm -rf $1/app/Music
rm -rf $1/priv-app/QuickSearchBox
rm -rf $1/priv-app/MiService
rm -rf $1/priv-app/MiGameCenterSDKService
rm -rf $1/app/Mipay
rm -rf $1/app/MiLinkService2
rm -rf $1/app/DeskClock
rm -rf $1/app/Cit
rm -rf $1/product/app/aiasst_service
rm -rf $1/product/app/talkback
#rm -rf $1/product/priv-app/GmsCore
rm -rf $1/product/priv-app/GooglePlayServicesUpdater
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/Backup
rm -rf $1/priv-app/CloudBackup
rm -rf $1/priv-app/Mirror
rm -rf $1/priv-app/MiService
rm -rf $1/priv-app/MiuiGallery
rm -rf $1/app/BsGameScript
rm -rf $1/app/BSGameService
rm -rf $1/app/BsLightApp
rm -rf $1/app/BsScreenLight
rm -rf $1/app/BsSound
rm -rf $1/app/CloudService
rm -rf $1/app/GameVpn
rm -rf $1/app/iFlyIME
rm -rf $1/app/KeyMapCenter
rm -rf $1/app/mab
rm -rf $1/app/mi_connect_service
rm -rf $1/app/Mipay
rm -rf $1/app/MiuiAccessibility
rm -rf $1/app/ModemTestBox
rm -rf $1/app/NdtCalibration
rm -rf $1/app/ShoulderKey
rm -rf $1/app/TouchAssistant
rm -rf $1/app/TSMClient
rm -rf $1/app/UPTsmService
rm -rf $1/app/VoiceAssist
rm -rf $1/app/VoiceTrigger
rm -rf $1/app/ZsGameDock
rm -rf $1/priv-app/BsPeripheral
rm -rf $1/priv-app/BsSearch
rm -rf $1/priv-app/Calendar
rm -rf $1/priv-app/GameLauncher
rm -rf $1/priv-app/I19tService
rm -rf $1/priv-app/MiGameCenterSDKService
rm -rf $1/priv-app/MiShare
rm -rf $1/priv-app/MiuiAod
rm -rf $1/priv-app/MiuiCamera
rm -rf $1/app/MiGalleryLockscreen
rm -rf $1/app/Email
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/MiuiVideoGlobal
rm -rf $1/app/wps-lite
rm -rf $1/priv-app/MiBrowserGlobal
rm -rf $1/priv-app/MiMover
rm -rf $1/priv-app/MiuiScanner
rm -rf $1/priv-app/QuickSearchBox
rm -rf $1/product/app/DeskClock
rm -rf $1/product/app/MiLinkService
rm -rf $1/product/app/Notes
rm -rf $1/product/app/SpeechServicesByGoogle
rm -rf $1/product/priv-app/Velvet
